### ISSUE TITLE
There is no completion list for .NET static methods

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#163] opened 2016-02-18 15:40 UTC
To repro try:
```powershell
[DateTime]::<ctrl+space>
```

**Comment by daviwil** [comment] 2016-02-18 15:43
Hah, yep, @dfinke were talking about this recently.  He's been looking into fixing it in VS Code.  From his last report, it sounds like VS Code is not asking for IntelliSense after the colon for whatever reason and then when you manually invoke it, the results aren't being displayed.  May need to file a bug on the VS Code team if we can't work around it.

**Comment by rkeithhill** [comment] 2016-02-18 17:16
So for instance members we get this request:
```javascript
    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 8,
      "method": "textDocument/completion",
      "params": {
        "uri": "file:///c%3A/Users/Keith/.vscode/extensions/ms-vscode.PowerShell-0.4.1/examples/DebugTest.ps1",
        "position": {
          "line": 1,
          "character": 3
        }
      }
    }
```
and give a response like this (elided)
```javascript
    {
      "jsonrpc": "2.0",
      "id": "8",
      "result": [
        {
          "label": "Date",
          "kind": 1,
          "detail": null,
          "documentation": "datetime Date { get; }",
          "sortText": null,
          "filterText": null,
          "insertText": "Date",
          "textEdit": {
            "range": {
              "start": {
                "line": 1,
                "character": 3
              },
              "end": {
                "line": 1,
                "character": 3
              }
            },
            "newText": "Date"
          },
          "data": null
        },
        ...
```
For static .NET members, Doug is right, we do get a request from VSCode:
```javascript
    {
      "jsonrpc": "2.0",
      "id": 12,
      "method": "textDocument/completion",
      "params": {
        "uri": "file:///c%3A/Users/Keith/.vscode/extensions/ms-vscode.PowerShell-0.4.1/examples/DebugTest.ps1",
        "position": {
          "line": 2,
          "character": 12
        }
      }
    }
```
and we response with (also elided):
```javascript
    {
      "jsonrpc": "2.0",
      "id": "12",
      "result": [
        {
          "label": "MaxValue",
          "kind": 1,
          "detail": null,
          "documentation": "static datetime MaxValue {get;}",
          "sortText": null,
          "filterText": null,
          "insertText": "MaxValue",
          "textEdit": {
            "range": {
              "start": {
                "line": 2,
                "character": 12
              },
              "end": {
                "line": 2,
                "character": 12
              }
            },
            "newText": "MaxValue"
          },
          "data": null
        },
        {
          "label": "MinValue",
          "kind": 1,
          "detail": null,
          "documentation": "static datetime MinValue {get;}",
          "sortText": null,
          "filterText": null,
          "insertText": "MinValue",
          "textEdit": {
            "range": {
              "start": {
                "line": 2,
                "character": 12
              },
              "end": {
                "line": 2,
                "character": 12
              }
            },
            "newText": "MinValue"
          },
          "data": null
        },
        ...
```
It seems like the PowerShell extension is performing correctly.

**Comment by dfinke** [comment] 2016-02-18 17:18
Yes, looks like vs code is not displaying a drop down with the suggestions.

**Comment by rkeithhill** [comment] 2016-02-18 17:20
So who's going to submit this to the VSCode team?  We have a simple repro.  :-)

**Comment by dfinke** [comment] 2016-02-18 17:21
It's best if comes from an insider ;-)


Sent from Outlook Mobile






On Thu, Feb 18, 2016 at 9:20 AM -0800, "Keith Hill" <notifications@github.com> wrote:





So who's going to submit this to the VSCode team?  We have a simple repro.  :-)

---

**Comment by daviwil** [comment] 2016-02-18 17:27
Seems like I've been elected ;) I'll file an issue when I get in to the office

**Comment by rkeithhill** [comment] 2016-02-18 17:48
While you're at it, submit another issue on debug data tips.  I've observed that scope plays some part here.  Global scope variable act flakey.  They maybe show once but not thereafter as long as we're executing in the same global scope.  As soon as I step into a function, the global variables pop debug data tips quite reliably.  Unfortunately, I then get no data tips for the variables inside the function I'm executing in.  And when there is not a data tip, it is because we never received a `variables` request from VSCode.  Every time we receive a `variables` request (not related to populating the variables view), a debug data tip appears.  I think we should be able to give the VSCode team a simple repro.

**Comment by rkeithhill** [comment] 2016-02-29 23:19
I'm putting this on the backlog for now as I'm pretty sure this isn't an extension bug. The corresponding [issue in VSCode ](https://github.com/Microsoft/vscode/issues/3153) doesn't have a milestone associated with it yet.

**Comment by daviwil** [comment] 2016-02-29 23:20
Sounds good!

**Comment by pcgeek86** [comment] 2016-03-31 06:36
Just ran into this problem myself. :frowning:

**Comment by daviwil** [comment] 2016-05-03 22:39
Hmm, I believe this will be fixed when VS Code 1.1.0 and PSES 0.6.0 is out, right @rkeithhill?

**Comment by rkeithhill** [comment] 2016-05-03 22:58
Well it works correctly with an alpha build of 1.1.0 from 4/28 against PSES 0.5.0.  Curiously, it doesn't work with the latest insiders build against PSES 0.5.0.  You get a completion list but the contents are not the static members.  So I guess it depends on which best represents what we will get with the 1.1.0 release of VSCode.

**Comment by daviwil** [comment] 2016-05-03 23:02
I'm guesing the current 1.1.0-insiders is what will end up getting shipped next week.  Alpha is probably the dev branch for 1.2.0.  Weird that it isn't working though, they fixed the bug for that version...

**Comment by rkeithhill** [comment] 2016-05-04 00:02
Maybe it also required a change on the extension side?  I was running against 0.5.0 and not 0.6.0.

**Comment by daviwil** [comment] 2016-05-04 00:03
Ahhh, right, we actually had a fix on our site that comes in 0.6.0.

**Comment by daviwil** [comment] 2016-05-11 00:35
This works for me in VS Code 1.1.0! :confetti_ball: I'm going to close this now.

**Closed by daviwil** 2016-05-11 00:35 UTC
Labels: bug

**Comment by pcgeek86** [comment] 2016-05-11 17:35
I also confirmed in 1.1.0-insider. David's not just fibbing! 😉 😜 

![image](https://cloud.githubusercontent.com/assets/466713/15190298/6504c286-176c-11e6-928b-f695cf126ff0.png)

**Comment by daviwil** [comment] 2016-05-11 17:36
And that's with the 0.5.0 extension installed?  Interesting, didn't think it'd work there too.  Good to know!

**Comment by pcgeek86** [comment] 2016-05-11 17:48
Freshly installed on a new install of Windows 10 Insider Build 14332! Yes, 0.5.
