### ISSUE TITLE
Debugger stops responding after a bit of debugging with watches defined

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#357] opened 2017-01-29 01:05 UTC
VS Code 1.8.1, PowerShell ext 0.9.0, Windows 10 AU.

I'm finding that if I have any watch defined, the debugger becomes unresponsive after hitting a few breakpoints.  I didn't see anything obvious in the log file.

[1485651267-212b9958-570a-4602-8228-df639d9e79441485647668037.zip](https://github.com/PowerShell/PowerShellEditorServices/files/737234/1485651267-212b9958-570a-4602-8228-df639d9e79441485647668037.zip)

**Comment by kapilmb** [comment] 2017-02-06 23:31
@rkeithhill Can you please provide me some snippet that I can use to reproduce this issue?

**Comment by rkeithhill** [comment] 2017-02-06 23:42
It is easy to repro.  Open up the Examples folder. Open DebugTest.ps1 and set a line breakpoint on the line `$i = $i + 1`.  Add a watch for `$i`.  Select the `PowerShell Launch (current file)` and press F5.  After the breakpoint is hit, press F5 to resume and the debugger never comes back.  Try starting the debugger again, and it is wedged.

**Comment by kapilmb** [comment] 2017-02-07 00:28
Thanks @rkeithhill

**Comment by daviwil** [comment] 2017-03-06 15:10
Looks like this was fixed in last Friday's Insider build, they don't send watch requests after the debugger resumes any longer.  I've got my own simple fix for the issue in the meantime, will add it to my PR.

**Closed** 2017-03-14 02:59 UTC
Labels: bug
