### ISSUE TITLE
Make Invoke-PSRLConstructor and Invoke-PSRLReadLine exported cmdlets

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellEditorServices#1296] opened 2020-05-24 20:14 UTC
When in a debug prompt... this PowerShell bug is exposed:
https://github.com/PowerShell/PowerShell/issues/12297

On this line:
https://github.com/PowerShell/PowerShell/blob/9212aac0fa020b657454ef4f9ff2fdd6fc6d759c/src/System.Management.Automation/engine/debugger/debugger.cs#L2360

Since we support 5.1... we have no option here but to revert https://github.com/PowerShell/PowerShellEditorServices/pull/1258

**Comment by TylerLeonhardt** [comment] 2020-05-24 20:16
This is until #1295 is done.

**Comment by ppainter1958** [comment] 2020-06-28 15:47
Having same issue as #2767, any suggested work around or timeframe to fix?

**Comment by rjmholt** [comment] 2020-06-28 18:30
> timeframe to fix

Working on the solution in https://github.com/rjmholt/PowerShellEditorServices/tree/async-ps-consumer, but it's a large work item and will likely require changes in PSReadLine to be released first, so won't be for some time.

**Comment by SydneyhSmith** [comment] 2020-07-09 17:10
Going to mark this as a duplicate of #1295

**Closed** 2020-07-10 18:00 UTC
Labels: Area-Engine, Resolution-Duplicate
