### ISSUE TITLE
ArgumentOutOfRangeException when pasting into terminal

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellEditorServices#989] opened 2019-07-02 17:01 UTC
When pasting text in the terminal, I'm frequently receiving an `ArgumentOutOfRangeException`. It's weird because it doesn't happen all the time but when it starts happening, it just keeps happening. 

Here's the output in the terminal.

```
PS F:\universal-dashboard\src\poshud> New-UDFab -Icon "plus" -size "large" -ButtonColor "red" -IconColor 'white' -Content { New-UDFabButton -Icon address_book
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 16.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.ReadLine(Boolean isCommandLine, CancellationToken cancellationToken)
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.StartReplLoop(CancellationToken cancellationToken)

PS F:\universal-dashboard\src\poshud>  -ButtonColor 'blue' -IconColor 'white' }
```

This is what I was trying to paste:

```
New-UDFab -Icon "plus" -size "large" -ButtonColor "red" -IconColor 'white' -Content { New-UDFabButton -Icon address_book  -ButtonColor 'blue' -IconColor 'white' }
```

As you can see it, it pasted the first half of the command, threw the exception and then pasted the second half of the command. What's weird is that it breaks at the exact same location every time I paste. 

Running Extension version 2019.5.0

Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by rjmholt** [comment] 2019-07-09 22:15
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/702. As we work toward integrating PSReadLine better we're hoping to fix this with that.

**Closed by rjmholt** 2019-07-09 22:15 UTC
Labels: Triage
