### ISSUE TITLE
Add diagnostic marker for dot-sourced file references that can't be found

### ISSUE THREAD

**Issue by kayladavis** [PowerShell/PowerShellEditorServices#9] opened 2015-08-11 23:40 UTC
When dot sourcing a file that doesn't exist, a semantics level diagnostic marker should be created so that the user knows they are referencing an incorrect file path.

**Comment by daviwil** [comment] 2016-12-06 18:32
This might be a nice Script Analyzer rule to add for a development ruleset, what do you think @kapilmb?

**Comment by kapilmb** [comment] 2016-12-06 18:34
Yes, it looks like such a rule will be useful indeed!

**Comment by kapilmb** [comment] 2016-12-07 02:46
Here is the issue: PowerShell/PSScriptAnalyzer#680

**Comment by tylerl0706** [comment] 2018-01-17 02:29
Closing this here since the issue is opened in ScriptAnalyzer.

**Closed by tylerl0706** 2018-01-17 02:29 UTC
Labels: Issue-Enhancement, Up-for-Grabs
