### ISSUE TITLE
v2.0.0-preview.6 fails with OmniSharp Error: System.InvalidOperationException: This operation is not supported for a relative URI.

### ISSUE THREAD

**Issue by ant-druha** [PowerShell/PowerShellEditorServices#1104] opened 2019-11-16 12:37 UTC
Full trace is 
```
2019-11-16 15:30:40.421 +03:00 [INF] highlight handler loaded
2019-11-16 15:30:40.472 +03:00 [DBG] Finding descriptor for initialize
2019-11-16 15:30:40.590 +03:00 [DBG] Starting: Routing Request (1) initialize
2019-11-16 15:30:40.598 +03:00 [DBG] Converting params for Request (1) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
2019-11-16 15:30:40.656 +03:00 [FTL] Failed to handle notification initialize
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.get_RootPath()
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<>c.<<StartAsync>b__18_3>d.MoveNext() in D:\a\1\s\src\PowerShellEditorServices\Server\PsesLanguageServer.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle(InitializeParams request, CancellationToken token)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
2019-11-16 15:30:40.674 +03:00 [DBG] Finished: Routing Request (1) initialize in 77ms
```
[EditorServices-IJ-2.log](https://github.com/PowerShell/PowerShellEditorServices/files/3854178/EditorServices-IJ-2.log)
[Start-EditorServices-EditorServices-IJ-2.log](https://github.com/PowerShell/PowerShellEditorServices/files/3854179/Start-EditorServices-EditorServices-IJ-2.log)

**Comment by TylerLeonhardt** [comment] 2019-11-16 19:36
@ant-druha does Intelij offer the ability to see the payloads of the requests that are being sent to and from it via the language server protocol?

I get the feeling that the issue here is that that is sending a relative path for the "rootPath" property of the [`initialize` request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#initialize)... where vscode _always_ sends absolute paths.

@david-driscoll @mholo65 this is a solid reason for https://github.com/OmniSharp/csharp-language-server-protocol/issues/181

**Comment by ant-druha** [comment] 2019-11-17 09:25
The path is absolute. Attached the dump file.
[protocol_messages_IJ.log](https://github.com/PowerShell/PowerShellEditorServices/files/3855425/protocol_messages_IJ.log)

**Comment by TylerLeonhardt** [comment] 2019-11-17 17:36
Thanks for the context @ant-druha and apologies for the issues here - it was a particularly large change that went into preview.6

Would you mind trying a build from master? I did make a change in the exact spot that threw the exception and am curious if the issue is already fixed.

**Comment by ant-druha** [comment] 2019-11-17 20:45
>Would you mind trying a build from master?
Sure @TylerLeonhardt Actually, could you advise how do I release the build package to try? Thanks.

**Comment by TylerLeonhardt** [comment] 2019-11-19 18:41
[PowerShellEditorServices.zip](https://github.com/PowerShell/PowerShellEditorServices/files/3865478/PowerShellEditorServices.zip)

Here you go 😄

**Comment by ant-druha** [comment] 2019-11-20 06:45
Thanks! But, unfortunately, same issue.
[EditorServices-IJ-0.log](https://github.com/PowerShell/PowerShellEditorServices/files/3867680/EditorServices-IJ-0.log)
[Uploading 

- Start-EditorServices-EditorServices-IJ-0.log…]()
[protocol_messages_IJ.log](https://github.com/PowerShell/PowerShellEditorServices/files/3867682/protocol_messages_IJ.log)

**Comment by TylerLeonhardt** [comment] 2019-11-20 07:02
[PowerShellEditorServices.zip](https://github.com/PowerShell/PowerShellEditorServices/files/3867764/PowerShellEditorServices.zip)

Sorry that last one didn't fix it - but I'm fairly confident this one will, @ant-druha!

**Comment by ant-druha** [comment] 2019-11-20 08:23
@TylerLeonhardt that did it! It fixed the reported issue. 

Unfortunately, I'm getting different error now, related to protocol messaging. Looks like my client gets unexpected content in incoming message:

```
Nov 20, 2019 11:17:51 AM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
SEVERE: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 499 path $.result.capabilities.codeActionProvider
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 499 path $.result.capabilities.codeActionProvider
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:116)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:78)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 499 path $.result.capabilities.codeActionProvider
	at com.google.gson.stream.JsonReader.nextBoolean(JsonReader.java:853)
	at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:144)
	at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:133)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 18 more
```

Need to investigate, may be some headers have changed. 

But anyway the initial issue is resolved. Thank you for your cooperation.
[protocol_messages_IJ.log](https://github.com/PowerShell/PowerShellEditorServices/files/3868090/protocol_messages_IJ.log)

**Comment by mholo65** [comment] 2019-11-20 09:25
@ant-druha The issue you are seeing is probably related to the the C# LSP implementation sends a `CodeActionOptions` instead of a `boolean` in the `ServerCapabilities` object during init. I know we have been bad at honoring the client requests during init regarding these. // cc @david-driscoll

```typescript
interface ServerCapabilities {
        ...
   
       /**
	 * The server provides code actions. The `CodeActionOptions` return type is only
	 * valid if the client signals code action literal support via the property
	 * `textDocument.codeAction.codeActionLiteralSupport`.
	 */
	codeActionProvider?: boolean | CodeActionOptions;

        ...
}
```

**Comment by ant-druha** [comment] 2019-11-20 11:32
@mholo65 I've updated lsp4j library to latest one and it worked. Thanks 👍

**Comment by TylerLeonhardt** [comment] 2019-11-20 15:10
@ant-druha so it sounds like you'll be unblocked and intellij-powershell will be able to use the next Preview? 😊

**Comment by ant-druha** [comment] 2019-11-20 16:01
Yes, this great! Not sure about bundled it yet, though. As this will not work with 5 and older versions. I might need to provide some hint for them.

**Comment by TylerLeonhardt** [comment] 2019-11-20 16:18
FWIW, the single telemetry data point we get from the vscode extension shows that almost no one is using v3 or v4 within their editor.

They might have v3 or v4 on a server somewhere, but they don't seem to be using it with the vscode extension.

**Comment by rjmholt** [comment] 2019-11-21 19:56
> As this will not work with 5 and older versions. I might need to provide some hint for them.

Should work with 5.1 and up. (5.0 hasn't been around for a while, since 5.1 was a mandatory upgrade)

**Comment by TylerLeonhardt** [comment] 2020-06-15 18:03
@ant-druha this should be working now. I'm gonna close this but let me know if you still see the issue!

**Closed by TylerLeonhardt** 2020-06-15 18:03 UTC
Labels: Area-Startup, Issue-Bug, Preview Extension
