### ISSUE TITLE
Formatting broken in 2020.04 Preview

### ISSUE THREAD

**Issue by mattpwhite** [PowerShell/PowerShellEditorServices#1257] opened 2020-04-10 00:14 UTC
I'm getting an NRE whenever I try to invoke the formatter in VS Code with the 2020.04 preview extension in VS Code.  This seems to be reproducible with a simple test file with a hashtable in it.  Logs look like this:

```
o  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Found attributes 1, powershell::file:///c:/local/test.ps1
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Looking for handler for descriptors textDocument/formatting
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Checking handler textDocument/formatting:Microsoft.PowerShell.EditorServices.Handlers.DocumentFormattingHandlers
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentFormattingRegistrationOptions
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Document Selector [powershell], [pwsh], [ps1], [psm1], [psd1], [**/*.ps*1]
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Handler Selected: Microsoft.PowerShell.EditorServices.Handlers.DocumentFormattingHandlers via [powershell], [pwsh], [ps1], [psm1], [psd1], [**/*.ps*1] (targeting OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentFormattingParams, OmniSharp.Extensions.LanguageProtocol, Version=0.16.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022],[OmniSharp.Extensions.LanguageServer.Protocol.Models.TextEditContainer, OmniSharp.Extensions.LanguageProtocol, Version=0.16.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]])
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter: Starting: Routing Request (29) textDocument/formatting
[Info  - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter: Converting params for Request (29) textDocument/formatting to OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentFormattingParams
[Info  - 8:04:32 PM] Microsoft.PowerShell.EditorServices.Services.WorkspaceService: Resolved path: file:///c:/local/test.ps1
[Info  - 8:04:32 PM] Microsoft.PowerShell.EditorServices.Handlers.DocumentFormattingHandlers: Created formatting hashtable: {"Rules":{"PSUseConsistentWhitespace":{"CheckOpenParen":true,"CheckSeparator":true,"CheckOpenBrace":true,"CheckOperator":true,"Enable":true,"CheckPipe":true,"CheckInnerBrace":true},"PSUseConsistentIndentation":{"Kind":"space","Enable":true,"PipelineIndentation":0,"IndentationSize":4},"PSPlaceOpenBrace":{"NewLineAfter":true,"Enable":true,"IgnoreOneLineBlock":true,"OnSameLine":true},"PSUseCorrectCasing":{"Enable":true},"PSAlignAssignmentStatement":{"CheckHashtable":true,"Enable":true},"PSPlaceCloseBrace":{"NewLineAfter":false,"Enable":true,"IgnoreOneLineBlock":true}},"IncludeRules":["PSPlaceCloseBrace","PSPlaceOpenBrace","PSUseConsistentWhitespace","PSUseConsistentIndentation","PSAlignAssignmentStatement"]}
[Error - 8:04:32 PM] OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter: Failed to handle notification textDocument/formatting - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.EditorServices.Handlers.DocumentFormattingHandlers.<Handle>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__9.MoveNext()
```

**Comment by TylerLeonhardt** [comment] 2020-04-10 00:18
This is a dupe of https://github.com/PowerShell/vscode-powershell/issues/2543#issuecomment-611540450

Of which I can't seem to repro... 

Can you follow the steps I've mentioned in that issue and let me know what you get? Let's use the other info to track this since that has more information.

**Closed** 2020-04-10 00:18 UTC
