### ISSUE TITLE
Exception in log during debug - debugger acting non-responsive

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#345] opened 2017-01-19 03:08 UTC
This is the stack trace (I've attached the full log file):
```
1/18/2017 7:58:19 PM [ERROR] - Method "ExecuteCommand" at line 476 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Runtime exception occurred while executing command:
    
    System.Management.Automation.CmdletInvocationException: The scope number '3' exceeds the number of active scopes.
    Parameter name: scopeID
    Actual value was 3. ---> System.Management.Automation.PSArgumentOutOfRangeException: The scope number '3' exceeds the number of active scopes.
    Parameter name: scopeID
    Actual value was 3.
       at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
       at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
       at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
       at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
       at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
       at System.Management.Automation.CommandProcessor.ProcessRecord()
       --- End of inner exception stack trace ---
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
       at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
       at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
       at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
       at System.Management.Automation.PowerShell.InvokeWithDebugger(IEnumerable`1 input, IList`1 output, PSInvocationSettings settings, Boolean invokeMustRun)
       at System.Management.Automation.ScriptDebugger.ProcessCommand(PSCommand command, PSDataCollection`1 output)
       at Microsoft.PowerShell.EditorServices.Session.PowerShell4Operations.ExecuteCommandInDebugger[TResult](PowerShellContext powerShellContext, Runspace currentRunspace, PSCommand psCommand, Boolean sendOutputToHost)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteCommandInDebugger[TResult](PSCommand psCommand, Boolean sendOutputToHost)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommand>d__40`1.MoveNext()
```
I just updated to the latest of PSES and vscode-powershell and am using those bits.

[1484794581-d6e1949c-04ff-4ef8-9f75-620ba66b16ba1484794578279.zip](https://github.com/PowerShell/PowerShellEditorServices/files/715588/1484794581-d6e1949c-04ff-4ef8-9f75-620ba66b16ba1484794578279.zip)

**Comment by kapilmb** [comment] 2017-02-10 20:00
Can you please provide steps for reproducing this case. I looked at the logs and it appears `posh-git\test\testDebugHarness.ps1` was being debugged but I cannot reproduce the hang.

**Comment by tylerl0706** [comment] 2018-01-12 03:04
I don't think this repros anymore, does it @rkeithhill?

**Comment by rkeithhill** [comment] 2018-01-12 03:15
I think I fixed this a while back.  If not, keep an eye out for:
```
PSArgumentOutOfRangeException: The scope number 'n' exceeds the number of active scopes.
```
In log files.

**Comment by tylerl0706** [comment] 2018-01-12 03:17
Sounds good. Closing for now.

**Closed by tylerl0706** 2018-01-12 03:17 UTC
Labels: Area-Debugging, Issue-Bug

**Comment by glen-nicol** [comment] 2018-06-09 00:31
My coworker and I see this in our VS code output. I am using 1.7.0 of the powershell extension and 1.23.1 of VS code on windows.

```
The scope number '2' exceeds the number of active scopes.
Parameter name: scopeID
Actual value was 2.
The scope number '1' exceeds the number of active scopes.
Parameter name: scopeID
Actual value was 1.
```

Our scripts may be doing something unconventional though. We have scripts calling other scripts like this:
```powershell
& $deployscript -deployment_dir $packageDir -actionType $actionType -configuration $configuration
```

We do not see these errors if we run through normal powershell prompt/ command line.

Where would I look for log files to help you guys narrow down root cause?

**Comment by tylerl0706** [comment] 2018-06-09 23:33
Strange... These steps would be a good place to start!:
https://github.com/powershell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by glen-nicol** [comment] 2018-06-11 16:53
[logs.zip](https://github.com/PowerShell/PowerShellEditorServices/files/2090946/logs.zip)
I replaced the paths with what I think are equivalent substitutes. 
I didn't see it anywhere in the logs. I am running PS 3.0 on Win7.
