### ISSUE TITLE
Tab complete on ParameterAttribute property Value erases text

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#63] opened 2015-12-09 03:58 UTC
This is what I'm seeing:
![tabcompletebug1](https://cloud.githubusercontent.com/assets/5177512/11676273/2e031d70-9dee-11e5-93ca-f7ad04940c90.png)
If I press tab at this point, I wind up with:
![tabcompletebug2](https://cloud.githubusercontent.com/assets/5177512/11676276/37ab5996-9dee-11e5-9789-4bbe030cc45b.png)
:-(

**Comment by daviwil** [comment] 2015-12-09 04:07
Yeah, there's a general class of bugs caused by the completion code in Editor Services:

https://github.com/PowerShell/vscode-powershell/issues/12
https://github.com/PowerShell/vscode-powershell/issues/45

This is coming from the code here:  https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Host/LanguageServer.cs#L375

I'm using ScriptAst.FindAll to locate the token which is currently being completed.  Apparently my algorithm there needs some more cases (or needs to be converted into an AstVisitor) so that I identify these cases that are currently being completed incorrectly.  The idea is that I'd find the ScriptExtent of the token being completed so that I can return an edit that can be applied in the editor when the user selects that completion.

If you've got an ideas on how to improve that, I'd love to hear them!

**Comment by daviwil** [comment] 2015-12-11 18:22
Fixed with commit e3d46b5

**Closed by daviwil** 2015-12-11 18:22 UTC

**Comment by rkeithhill** [comment] 2015-12-11 19:39
Thanks!
