### ISSUE TITLE
The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.

### ISSUE THREAD

**Issue by rachaelsingleton** [PowerShell/PowerShellEditorServices#1387] opened 2020-11-11 14:26 UTC
I am getting the following error when using visual studio code & powershell 7 and running a commandlet. 

The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.

I do not get this error in the native PowerShell 7 terminal (outside of VS Code).

**Comment by rjmholt** [comment] 2020-11-11 17:28
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/3057

**Closed by rjmholt** 2020-11-11 17:28 UTC
Labels: Needs: Triage :mag:
