### ISSUE TITLE
Auto Completion Suggestions for type members seems unaware of the context

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShellEditorServices#1910] opened 2022-08-26 00:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Note I have the following `using` context.

```ps1
using namespace System.Data
using namespace System.Data.OleDb
```

When the completions suggestion auto fires after the `::` is typed, it only shows recent input.
```ps1
[OleDbType]::
```
![image](https://user-images.githubusercontent.com/26179051/186791053-b10cb477-d9ea-4cc2-b5f0-9e79895f96e5.png)

It seems unaware of the current context, possibly that the event trigger of pressing `:` twice doesn't wait for the context to be resolved before offering suggestions.   If the suggestion box is cancelled and completions are requested manually, then the suggestions are relevant to the context.

![image](https://user-images.githubusercontent.com/26179051/186791396-31a6ee95-3c64-459d-b635-8529adb18841.png)

### Environment data

```
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core 
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

v2022.8.4

**Comment by SeeminglyScience** [comment] 2022-09-23 19:12
Duplicate of #1810

**Comment by SeeminglyScience** [comment] 2022-09-23 19:12
Thanks for the report! This is a known issue being tracked in PowerShell/PowerShellEditorServices#1810. 

For a temporary workaround, you can press <kbd>Ctrl</kbd> + <kbd>Space</kbd> when it happens. If that just comes up saying "no completions" you can usually press <kbd>Esc</kbd> to close the completions window and then <kbd>Ctrl</kbd> + <kbd>Space</kbd> to trigger it again.

**Closed** 2022-09-24 22:01 UTC
Labels: Issue-Bug, Resolution-Duplicate
