### ISSUE TITLE
'Run tests|Debug tests' Pester code lens does not show when Describe block is interpolated string

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShellEditorServices#827] opened 2018-12-15 14:48 UTC
I sometimes include test details in the describe block that are sometimes only known at runtime, however, the Pester code lens does not show any more once I use an interpolated string in the Describe block.
Given the following Pester file (`foo.tests.ps1`):
```powershell
$version = $PSVersionTable.PSVersion.Major
Describe "foo on PSVersion $version" {
	It "bar $version" {

	}
}
```

The `Run tests|Debug tests` code lens does not show, I see that under the hood, the extension creates parameters to `Invoke-Pester` that look like `-PesterOption @{IncludeVSCodeMarker=$true} -TestName 'foo'`, in this case, the extension would either need to evaluate the interpolated string or just get rid of the `-TestName` parameter.

**Comment by rjmholt** [comment] 2018-12-17 19:39
Evaluating the string will either be tricky or dangerous, so I think if we can pass this off to Pester we should.

**Comment by rkeithhill** [comment] 2018-12-17 22:06
What if we created the command line using double quotes e.g. `-PesterOption @{IncludeVSCodeMarker=$true} -TestName "foo on PSVersion $version"`?  Or maybe if we can pull the string from the Describe block that would be better.  That way if you used single quotes to prevent interpolation, we'd honor that.

**Comment by bergmeister** [comment] 2018-12-20 10:19
Interestingly the single quote is by design, which [this](https://github.com/PowerShell/vscode-powershell/issues/891) issue documents as it used to be double quotes but was not working for interpolated strings, which I do not understand, maybe there was even a bug in Pester since the issue is quite old.

**Comment by rkeithhill** [comment] 2019-01-11 03:44
@SeeminglyScience and I had a discussion on the Slack where I think we came to the conclusion there is no good way to support interpolated strings.  Many times the variables used in the TestName interpolated string are defined in the test file.  However, we must provide a string to Invoke-Pester -TestName that gets executed in the PS integrated console. So we have a catch 22, the variable doesn't get defined until the test executes, but we can't successfully execute the test by name because the variable is not defined yet.  

I think the best we can do here is change the code lens for the Describe block to offer to run all tests in the file.  This would probably be better than silently not offering anything.

**Comment by nohwnd** [comment] 2019-01-11 15:06
Yes, there is [v5-alpha1](https://github.com/nohwnd/Pester/tree/new-runtime) since yesterday that can discover tests and filter them by `It`, and only run appropriate setups and teardowns, so it should be ideal for running tests selectively. 

It already can filter by path, you can see me do someting very similar with [re-running failed tests here](https://github.com/nohwnd/Pester/blob/3f875d983142ea2350b63ad3a524aaee1f490a6b/new-runtimepoc/Pester.Runtime.Tests.ps1#L468).

At the moment those published functions do not take the result object + paths (to keep the api smaller and simpler), instead test discovery is done every time from scratch. 

But internally the limitation is not there, if I add functions that clean a dirty discover/run result, it could easily take a cached discovery object and run with different filters.  Which is useful not only for this scenario, but for example if you want to observe filesystem, discover tests in a single file, join that discovery result to you cached results and re-run all previously failed tests in all files. Or when you have a huge test suite where discovery takes signifcant amount of time, and multiple configurations to run it with.

**Comment by rjmholt** [comment] 2019-01-11 17:50
> I'm still very uneasy about the idea of some of the code lenses running all tests and some running only the nearest describe block. I'd much rather see a descriptive error message explaining that the test name should be static.

I 100% agree. I think executing the CodeLens should always do the same thing or fail informatively.

The truth is that you can embed arbitrary expressions in PowerShell strings. But executing a Pester CodeLens, you're going to execute arbitrary code anyway. So maybe we should just get PowerShell to evaluate the string when we think it's not static? Except the big problem there is that executing a single test in a vacuum will quite likely not have the variable populated. Which is a scenario I don't think we should aim to support -- there's nothing easy about trying to reconstruct arbitrary execution states so that variables exist for interpolation.

So personally I would be happy with any of:
- We reject non-static strings, have a nice informative message saying this, and take the philosophy that parameterised tests don't make sense being plucked out of a file and run individually with the CodeLens (the term "Lens" implies you've lost outside context to me as well).
- We have a heuristic to identify non-static strings and try to evaluate them in our currently PowerShell context when we see them to instantiate the Pester CodeLens name. It will frequently give a different result to running the whole test script and people will expect it to work when it doesn't, but we just would take the line that we meet them halfway and can't take it any further because we can't pick apart the mixing of imperative and declarative paradigms.

**Comment by SeeminglyScience** [comment] 2019-01-11 18:10
> So maybe we should just get PowerShell to evaluate the string when we think it's not static? Except the big problem there is that executing a single test in a vacuum will quite likely not have the variable populated.

Yeah, every example I've seen so far has had the variable defined at the top of the test file. More specifically, it's not even going to be defined at the point we run `Invoke-Pester`.

For example:

```powershell
# Invoke-MyCommand.Tests.ps1
$CommandName = $MyInvocation.MyCommand.Name.Replace('Tests.ps1', '')

Describe "$CommandName Integration Tests" {
    # ...
}
```

If we get PowerShell to evaluate:

```powershell
Invoke-Pester Invoke-MyCommand.Tests.ps1 -TestName "$CommandName Integration Tests"
```
Then `TestName` will evaluate to ` Integration Tests`. The only way I could see that being supportable is if the `TestName` could take a `ScriptBlock` as an argument (or if the discovery object scenario @nohwnd described would support that)

**Comment by rjmholt** [comment] 2019-01-11 18:21
Playing with this a bit more:

```powershell
$duck = 'Hello'

Describe "My test $duck" {
    It "works" {
        1 | Should -Be 1
    }
}
```

There's no way to execute the test with `Invoke-Pester ./My.Tests.ps1 -TestName <name>` here without knowing what the value of `$duck` is statically. To make Pester execute it, we need `Invoke-Pester ./My.Tests.ps1 -TestName 'My test Hello'`. Since the CodeLens execute button is executed outside of the file, we can't just ever make it work in general -- and I think it's worth noting that this is a limitation that exists for Pester without our CodeLens too (not saying it should work, just that the problem is one of expecting runtime information to be known statically).

Circling back to the original problem statement:
> I sometimes include test details in the describe block that are sometimes only known at runtime

I think "only known at runtime" defines this problem as out of scope for something based on AST analysis. If it's *only* known at runtime, then there's no way for us to ask Pester to execute this.

**Comment by SeeminglyScience** [comment] 2019-01-11 19:06
> 2. We don't add CodeLens to Describes with variables in them

I'd say *do* add the code lens, but write a descriptive error message.  A rule works too I suppose but that's more default stuff folks would need to suppress.

**Comment by TylerLeonhardt** [comment] 2019-01-11 19:23
Yeah that sounds good. I like the idea of a PSSA rule in addition to the descriptive error message so users can correct the issue before it happens 👍

**Comment by rkeithhill** [comment] 2019-01-11 19:57
Does VSCode support adding an error message in place of a code lens?

**Comment by TylerLeonhardt** [comment] 2019-01-11 21:15
@rkeithhill if it doesn't, we can just still show the codelens and have it display an error when clicked.

**Comment by nohwnd** [comment] 2019-01-13 08:59
@bergmeister do you want to try implementing this so it filters on path+line? The implementation in Pester should be very simple (plus you already know the codebase), and you'd get some practice in TS. I'd accept a PR for it.

**Comment by nohwnd** [comment] 2019-01-14 07:57
@bergmeister Not sure what exactly you mean. Invoke some setup that already is in the file? Or some setup that you externally provide? Before All Describe/Context/It you mean once, or once per file, or on every Describe/Context/It?

**Closed** 2019-01-18 17:44 UTC
Labels: Area-CodeLens, Area-Pester, Issue-Enhancement

**Comment by rkeithhill** [comment] 2019-01-18 22:18
> So what I am thinking is that you pass the line on which the opening brace of the test scriptblock is {

Does Pester support this yet?  When it does, it would be easy for us to make the change over to invoking tests by line number instead of test name.

**Comment by nohwnd** [comment] 2019-01-18 22:20
@rkeithhill it does not, yet. If I have some time I will code it for 4.5.1 over the weekend
