### ISSUE TITLE
"$("(")" is reporting 'the string is missing the terminator: ".' and "$(subexpression) is missing the closing ')'."

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/PowerShellEditorServices#101] opened 2016-01-04 03:07 UTC
This expression is causing two errors with syntax parsing in VS-Code:
* 'the string is missing the terminator: ".
* $(subexpression) is missing the closing ')'.
```powershell
"$("(")"
```

Maybe there is some weirdness with bare ( in PowerShell string literals that I'm not aware of, but this seems wrong to me. No amount of escaping seems to resolve the issue, either. In the PowerShell prompt, pressing Enter after entering this text displays the multi-line input prompt, indicating that the shell also thinks the input is incomplete.

This repros with any size string literal, as long as there is an unbalanced OPEN parentheses inside the string.

**Comment by MikeShepard** [comment] 2016-01-04 03:20
When I enter that in the ISE (5.0), I get an error about the subexpression missing the closing ).

**Comment by MikeShepard** [comment] 2016-01-04 03:30
To me, this looks like a double-quoted string with a subexpression $( started, then a closing double-quote.  That's an error.

After that, there's a left paren and a right paren in quotes, but no closing paren (since the right one was in quotes).

**Comment by AndrewGaspar** [comment] 2016-01-04 03:48
Maybe this example is more clear. It also repros the issue.
```powershell
"$(" some text here ( and also here ")"
```

**Comment by MikeShepard** [comment] 2016-01-04 03:59
The way I parse it (and PowerShell seems to agree) is a $( inside double-quotes followed by some other stuff.

I don't know of a way to include a double-quoted string literal in a subexpression in a double-quoted string.

I would think replacing the "inner" double quotes with single quotes would work, but it doesn't:
"$(' a string literal'  + ' some text here ( and also here ')"

that gives the same error.  I think that is actually a bug, but I don't think the same thing with double quotes inside.

does that make sense?

**Comment by rkeithhill** [comment] 2016-01-04 04:41
You can put a double quoted string inside of a sub-expression inside of a double quoted e.g.:
```powershell
"$("foo`nbar`n"*2)"
```
Regardless the apparent bug in parsing is not a bug with this extension as it is using the same parser/AST that the console's PSReadLine and ISE are using.  Both of which choke on the same unbalanced paren.  

You should file this bug on the [PowerShell UserVoice site](https://windowsserver.uservoice.com/forums/301869-powershell)

**Comment by AndrewGaspar** [comment] 2016-01-04 04:52
Sounds like PowerShell needs to be open sourced! ;)

Bug filed here: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11297838-parsing-error-on

**Comment by daviwil** [comment] 2016-01-04 16:17
Great discussion!  I'll close this issue since Andrew has filed the issue on the UserVoice site.

**Closed by daviwil** 2016-01-04 16:17 UTC
