### ISSUE TITLE
Bad tab completion suggestions in Integrated Console

### ISSUE THREAD

**Issue by lc9er** [PowerShell/PowerShellEditorServices#1356] opened 2020-09-12 00:56 UTC
OS: Win10 1909
VSCode: 1.49.0
Powershell Extension: 2020.6
PowerShellEditorServices.psd1: 2.1.0

Description:

When I enter a remote PSSession, type a command like `cd`, `ls`, or others, then hit `Tab` to cycle through completion options, I get listings of files and directories from the local directory I was in *before* entering the remote session.

Expected Behavior:

I should get completion options for the current remote directory.

Additional Notes:

I don't see this behavior when using `powershell.exe`, `pwsh`, or the built-in terminal in VSCode. I *do* see the same behavior when I use the Integrated Terminal in the coc-powershell extension in Neovim.

**Comment by rjmholt** [comment] 2020-09-28 17:44
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2661

**Closed** 2020-09-29 18:00 UTC
Labels: Resolution-Duplicate
