### ISSUE TITLE
HereStrings breaks folding

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShellEditorServices#377] opened 2017-03-14 10:48 UTC
![image](https://cloud.githubusercontent.com/assets/3505151/23897056/047b6424-08ac-11e7-8d60-ee4292da5294.png)

Folding should be at the beginning of the here string and not at the end.

**Comment by daviwil** [comment] 2017-03-21 17:04
Hey Staffan, sorry for the delay.  This is part of the general class of folding issues caused by VS Code's naive indentation-based code folding implementation.  [This issue](https://github.com/Microsoft/vscode/issues/3422) will need to be fixed before here strings will be folded correctly.

**Comment by daviwil** [comment] 2017-03-21 17:05
Going to close this issue since it's not something Editor Services can help with at the moment.

**Closed by daviwil** 2017-03-21 17:05 UTC
